{{- if .Values.rds.analytics_enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: analytics-database-preparation
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - >
            echo Creating analytics database...;
            export PGPASSWORD={{ .Values.rds.masterPassword | quote }};
            echo "SELECT 'CREATE DATABASE $rds_analytics_db_name' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$rds_analytics_db_name')\gexec" | psql -h $rds_writer -d postgres -U $rds_master_username
        env:
          - name: rds_writer
            value: {{ .Values.rds.writer_endpoint }}
          - name: rds_master_username
            value: {{ .Values.rds.masterUsername }}
          - name: rds_app_user_password
            value: {{ .Values.rds.appUserPassword | quote }}
          - name: rds_analytics_db_name
            value: {{ .Values.rds.analytics_db_name | quote }}
          
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      restartPolicy: Never
{{- end }}