# Default values for database-preparation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: Always
  tag: latest
  imagePullSecrets: ""

rds:
  analytics_enabled: false
  byor_enabled: false
  writer_endpoint: ""
  masterUsername: ""
  masterPassword: ""
  analytics_db_name: "analytics"
  byor_db_name: "byor"
